# DO NOT EDIT THIS FILE
# All site-specific configuration should be stored in spsid_siteconfig.pl

use lib(@perllibdirs@);


$SPSID::Config::backend = 'SPSID::Backend::SQL';

             

@SPSID::Config::object_validators =
    (sub {
         my $attr = shift;
         if( $attr->{'spsid.object.class'} =~ /^SIAM\:\:/o ) {
             foreach my $name ('siam.object.complete') {
                 if( not defined($attr->{$name}) ) {
                     die('Missing attribute: ' . $name .
                         ' in spsid.object.id=' . $attr->{'spsid.object.id'});
                 }
             }
         }
     },
    );

                               
                                     

$SPSID::Config::object_attributes =
{
 '_mandatory' =>
 {
  'spsid.object.id' => 1,
  'spsid.object.class' => 1,
  'spsid.object.container' => 1,
 },
 '_unique' =>
 {
  'spsid.object.id' => 1,
 },
  
 'SIAM::Contract' =>
 {
  '_mandatory' =>
  {
   'siam.contract.inventory_id' => 1,
   'siam.contract.customer_name' => 1,
  },
  '_unique' =>
  {
   'siam.contract.inventory_id' => 1,
  },
 },

 'SIAM::Service' =>
 {
  '_mandatory' =>
  {
   'siam.svc.product_name' => 1,
   'siam.svc.type' => 1,
   'siam.svc.inventory_id' => 1,
  },
  '_unique' =>
  {
   'siam.svc.inventory_id' => 1,
  },
 },

 'SIAM::ServiceUnit' =>
 {
  '_mandatory' =>
  {
   'siam.svcunit.name' => 1,
   'siam.svcunit.type' => 1,
   'siam.svcunit.inventory_id' => 1,
  },
  '_unique' =>
  {
   'siam.svcunit.inventory_id' => 1,
  },
 },

 

  
};


  
 

  

                                      
                 
                                     




if( defined($ENV{'SPSID_SITECONFIG'}) ) {
    require $ENV{'SPSID_SITECONFIG'};
}
else {
    require '@siteconfdir@/spsid_siteconfig.pl';
}

  

1;


# Local Variables:
# mode: cperl
# indent-tabs-mode: nil
# cperl-indent-level: 4
# cperl-continued-statement-offset: 4
# cperl-continued-brace-offset: -4
# cperl-brace-offset: 0
# cperl-label-offset: -2
# End:
