DELETE FROM SPSID_OBJECT_ATTR
WHERE OBJECT_ID IN (SELECT OBJECT_ID FROM SPSID_OBJECTS WHERE SPSID_OBJECTS.OBJECT_DELETED=1);

DELETE FROM SPSID_OBJECT_LOG
WHERE OBJECT_ID IN (SELECT OBJECT_ID FROM SPSID_OBJECTS WHERE SPSID_OBJECTS.OBJECT_DELETED=1);

DELETE FROM SPSID_OBJECTS WHERE SPSID_OBJECTS.OBJECT_DELETED=1;

COMMIT;
